@host = http://localhost:5028

### Register
POST {{host}}/api/user/register/
Accept: application/json
Content-Type: application/json

{
  // "username": "test", "password": "test"
}

### Login
POST {{host}}/api/user/login/
Accept: application/json
Content-Type: application/json

{
  // "username": "test", "password": "test"
}

### Get user by id
GET {{host}}/api/user/get-user/id/1
Accept: application/json

### Get user by username
GET {{host}}/api/user/get-user/username/test
Accept: application/json

### Create Post
POST {{host}}/api/post
Accept: application/json
Content-Type: application/json

{
  // "title": "Titre", "content": "Contenu", "userId": 1
}

### Get all posts
GET {{host}}/api/post
Accept: application/json

### Get post by id
GET {{host}}/api/post/1
Accept: application/json

### Update post
PUT {{host}}/api/post/1
Accept: application/json
Content-Type: application/json

{
  // "id": 1, "title": "Nouveau titre", "content": "Nouveau contenu", "userId": 1
}

### Delete post
DELETE {{host}}/api/post/1
Accept: application/json

### Get category by id
GET {{host}}/api/category/get-category/1
Accept: application/json

### Get all categories
GET {{host}}/api/category/get-all-categories/
Accept: application/json

### Create category
POST {{host}}/api/category/create-category/
Accept: application/json
Content-Type: application/json

{
  // "name": "Nom de la catégorie"
}