@MonApiBackend_HostAddress = http://localhost:5028

// Register
POST {{MonApiBackend_HostAddress}}/register
Accept: application/json
Content-Type: application/json

// Login
POST {{MonApiBackend_HostAddress}}/login
Accept: application/json
Content-Type: application/json

// Create Post
POST {{MonApiBackend_HostAddress}}/create-post
Accept: application/json
Content-Type: application/json

// Get Posts
GET {{MonApiBackend_HostAddress}}/get-posts
Accept: application/json
Content-Type: application/json

GET {{MonApiBackend_HostAddress}}/get-posts-by-user
Accept: application/json
Content-Type: application/json


// Delete Post
POST {{MonApiBackend_HostAddress}}/delete-post  
Accept: application/json
Content-Type: application/json

POST {{MonApiBackend_HostAddress}}/create-comment
Accept: application/json
Content-Type: application/json

POST {{MonApiBackend_HostAddress}}/create-reply
Accept: application/json
Content-Type: application/json

POST {{MonApiBackend_HostAddress}}/upvote
Accept: application/json
Content-Type: application/json

POST {{MonApiBackend_HostAddress}}/downvote
Accept: application/json
Content-Type: application/json




###
