apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5028
      targetPort: 5028
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-external
  namespace: default
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5028
      targetPort: 5028
      nodePort: 30028
  type: NodePort
